### ISSUE TITLE
Viewport が画面より大きい時に明示的に縮小させたい

### ISSUE THREAD

**Issue by curegit** [curegit/nagoya#33]
Viewport 設定に `initial-scale=1` を付加したときでも、明示的に 420px 以下で自動縮小されるようにしたい。
現在は `initial-scale=1` を外し、ブラウザの挙動依存で実現している。
zoom のサポートに不安があるのと、単位付き除数がほぼ使えない、Windows でスクロールバーを外した横幅が取れないので、見送る。

```css
@media (max-width: 420px) {
  :root {
    zoom: calc(100vw / 420px);
  }
}
```
